### PR TITLE
Fix phantom HackGT logo appearing on slow connections

### LINKED ISSUE #62: Large HackGT logo showing up on home screen sometimes
screenshot 6

### PR DESCRIPTION
**Pull request by petschekr**
Due to a race condition, a second HackGT logo SVG will be downloaded if the initial download takes more than 100 ms to complete.

To reproduce, open dev tools in Chrome or Firefox, disable cache, and throttle network to 3G or lower.

Fixes #62

### CODE REVIEW

**Comment by bunsenmcdubbs** [comment]
🙏 🙏 🙏 OMG this isn't just a ghost

File: js/home.js [hunk 1]
```diff
@@ -185,15 +186,19 @@ function init() {
...
-        // note, when adding an SVG, make sure the height/width/viewbox attributes from the top svg node are removed from the actual .svg file
-        Snap.load('./assets/hackgt.svg', function(loadedFragment) {
-            s.append(loadedFragment);
-            logo = s.select('#hackgt');
-            // useFilters && logo.attr({filter: lightShadow});
-            logo.attr({filter: logoShadow});
-            logo.attr({fill: logoColor});
-            centerLogo();
-        });
+        if (!logoDownloadTriggered) {
```
Comment (jacobj10) [inline js/home.js:189]: Nit: don't really need to change but I guess this could just be `if (!logo && !logoDownloadTriggered)`

**Review by jacobj10 — APPROVED** [review]
LGTM, nice catch, merge when you're ready!

File: js/home.js (hunk 1 above)
Comment (petschekr) [reply js/home.js:189]: I didn't want to do that because otherwise it will jump to the else block and call `centerLogo()` which fails if the logo isn't loaded I think
